image: mhndev/docker-lua

before_script:
  - apt-get update && apt-get install -y libsqlite3-dev
  - luarocks install ldoc
  - luarocks install lsqlite3

stages:
  - test
  - build

pages:
  stage: build
  script:
    - ldoc --filter ldoc-dash.docset .
    - ldoc -f markdown --style ldoc-dash/ --template ldoc-dash/ --dir ./PICO-8.docset/Contents/Resources/Documents/ .
    - tar --exclude='.DS_Store' -cvzf PICO-8.tgz PICO-8.docset
    - sed -i "s/%VERSION%/$CI_COMMIT_REF/g" feed.xml
  artifacts:
    paths:
      - feed.xml
      - PICO-8.tgz
  only:
    - master

test:
  stage: test
  script:
    - ldoc --filter ldoc-dash.docset .
    - ldoc -f markdown --style ldoc-dash/ --template ldoc-dash/ --dir ./PICO-8.docset/Contents/Resources/Documents/ .
  except:
    - master